apiVersion: v1
kind: Service
metadata:
  labels:
    app: dimassi-informatique-backend-service
  name: backend
spec:
  ports:
  - port: 8081
  selector:
    service: dimassi-informatique-backend
  type: LoadBalancer
