apiVersion: v1
kind: Service
metadata:
  labels:
    app: Dimassi-Informatique-fService
  name: front
spec:
  ports:
  - port: 80
  selector:
    service: Dimassi-Informatique-frontend
  type: LoadBalancer